### ISSUE TITLE
Reflectable did not generate any files

### ISSUE THREAD

**Issue by cangSDARM** [Backendless/Flutter-SDK#8]
## Improvement
I followed [this](https://backendless.com/docs/flutter/data_data_object.html) official setup, but it didn't work.

So I had to search for reflectable related issues.

Then I got [this](https://stackoverflow.com/questions/51169706/flutter-reflection-with-reflectable-working-example-needed) solution. I think the official setup needs to upgrade to add some information about `build.yaml` to improve the user experience.

And this `build.yaml` works for me:

```yaml
targets:
  $default:
    builders:
      reflectable:
        generate_for:
          - lib/main.dart
        options:
          formatted: false
```
